services:
  client-prod:
    image: rookieanddocker/yogieat-client:latest
    container_name: yogieat-client-prod
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - yogieat-prod-network
    labels:
      - "name=client-prod"
      - "mode=production"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx-prod:
    image: rookieanddocker/yogieat-nginx:latest
    container_name: yogieat-nginx-prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot_conf_prod:/etc/letsencrypt-prod
      - certbot_www_prod:/var/www/certbot-prod
    depends_on:
      - client-prod
    networks:
      - yogieat-prod-network
    labels:
      - "name=nginx-prod"
      - "mode=production"
    restart: on-failure

  certbot-prod:
    image: certbot/certbot:latest
    container_name: yogieat-certbot-prod
    volumes:
      - certbot_conf_prod:/etc/letsencrypt
      - certbot_www_prod:/var/www/certbot
    networks:
      - yogieat-prod-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    labels:
      - "name=certbot-prod"
      - "mode=production"

networks:
  yogieat-prod-network:
    driver: bridge

volumes:
  certbot_conf_prod:
  certbot_www_prod:
