services:
  client-dev:
    image: rookieanddocker/yogieat-client:latest
    container_name: yogieat-client-dev
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - yogieat-dev-network
    labels:
      - "name=client-dev"
      - "mode=development"

  nginx-dev:
    image: rookieanddocker/yogieat-nginx:latest
    container_name: yogieat-nginx-dev
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - certbot_conf_dev:/etc/letsencrypt-dev
      - certbot_www_dev:/var/www/certbot-dev
    depends_on:
      - client-dev
    networks:
      - yogieat-dev-network
    labels:
      - "name=nginx-dev"
      - "mode=development"
    restart: on-failure

  certbot-dev:
    image: certbot/certbot:latest
    container_name: yogieat-certbot-dev
    volumes:
      - certbot_conf_dev:/etc/letsencrypt
      - certbot_www_dev:/var/www/certbot
    networks:
      - yogieat-dev-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    labels:
      - "name=certbot-dev"
      - "mode=development"

networks:
  yogieat-dev-network:
    driver: bridge

volumes:
  certbot_conf_dev:
  certbot_www_dev:
